# 导入numpy库并取别名为np (★☆☆)

In [1]:
import numpy as np

# 打印输出numpy的版本和配置信息 (★☆☆)

In [2]:
np.__version__

'1.19.2'

In [3]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/Anaconda3\\Library\\include']


# 创建一个长度为10的空向量 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 如何找到任何一个数组的内存大小？(★☆☆)

In [5]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# 如何从命令行得到numpy中add函数的说明文档? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [7]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 创建一个值域范围从10到49的向量(★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [9]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 创建一个 3x3 并且值从0到8的矩阵(★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

# 创建一个 3x3 的单位矩阵 (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 创建一个 3x3x3的随机数组 (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[0.44401316, 0.90623253, 0.11966209],
        [0.29478679, 0.40275633, 0.39452033],
        [0.84297563, 0.47678523, 0.50212078]],

       [[0.63083236, 0.73647596, 0.01027813],
        [0.70414772, 0.09973091, 0.72688966],
        [0.5211413 , 0.3380368 , 0.78429324]],

       [[0.79519883, 0.44428075, 0.26299408],
        [0.58466112, 0.86030125, 0.85894104],
        [0.67053586, 0.61200495, 0.42553959]]])

# 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [14]:
Z = np.random.random((10,10))
Z.min(), Z.max()

(0.0013829196889882933, 0.990141331955975)

# 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [15]:
Z = np.random.random(30)
Z.mean()

0.5671285008050789

# 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)

In [17]:
Z = np.ones((5,5))
np.pad(Z, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 下面表达式运行的结果是什么？(★☆☆)

In [18]:
0 * np.nan

nan

In [19]:
np.nan == np.nan

False

In [20]:
np.inf > np.nan

False

In [21]:
np.nan - np.nan

nan

In [22]:
0.3 == 3 * 0.1

False

# 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)

In [23]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [24]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [25]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

# 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [26]:
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 对一个5x5的随机矩阵做归一化(★☆☆)

In [27]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[0.57169997, 0.13240912, 0.54217469, 0.08253353, 0.43659318],
       [0.47383834, 0.62319864, 0.79187471, 0.88030639, 0.32294387],
       [0.11496205, 0.83488764, 0.23070872, 0.166234  , 0.1969877 ],
       [0.82482621, 0.44178235, 0.37838131, 0.00552655, 0.        ],
       [0.99080261, 0.61160718, 1.        , 0.6979947 , 0.99569168]])

# 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [28]:
np.dtype([("r", np.ubyte, 1),
          ("g", np.ubyte, 1),
          ("b", np.ubyte, 1),
          ("a", np.ubyte, 1)])

<ipython-input-28-6c4cf054cef1>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

# 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？(★☆☆)

In [29]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [30]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

# 下面脚本运行后的结果是什么? (★☆☆)

In [31]:
sum(range(5),-1)

9

In [32]:
np.sum(range(5),-1)

10

# 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)

In [33]:
Z = np.array([1,2,3])

In [34]:
Z**Z

array([ 1,  4, 27], dtype=int32)

In [35]:
2 << Z >> 2

array([1, 2, 4], dtype=int32)

In [36]:
Z <- Z

array([False, False, False])

In [37]:
1j*Z  # 复数

array([0.+1.j, 0.+2.j, 0.+3.j])

In [38]:
Z/1/1

array([1., 2., 3.])

In [39]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# 下面表达式的结果分别是什么？(★☆☆)

In [40]:
np.array(0) / np.array(0)

<ipython-input-40-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [41]:
np.array(0) // np.array(0)

<ipython-input-41-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [42]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

# 如何从零位开始舍入浮点数组？(★☆☆)

In [43]:
Z = np.random.uniform(-10,+10,10)
print(Z)
np.copysign(np.ceil(np.abs(Z)), Z)

[ 4.98948184  3.35249434  7.41145903 -7.28373889 -6.1166632  -1.20994144
  5.88711929  4.81129493 -1.83530811 -6.9606028 ]


array([ 5.,  4.,  8., -8., -7., -2.,  6.,  5., -2., -7.])

# 如何找出两个数组公共的元素? (★☆☆)

In [44]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(Z1)
print(Z2)
np.intersect1d(Z1, Z2)

[4 1 6 6 2 3 5 2 5 7]
[8 7 2 7 2 7 2 6 6 0]


array([2, 6, 7])

# 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [45]:
# 开启
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
# 恢复
_ = np.seterr(**defaults)

In [46]:
# 另一个等价的方式， 使用上下文管理器（context manager）
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

# 下面的表达式是否为真? (★☆☆)

In [47]:
np.sqrt(-1) == np.emath.sqrt(-1)  # 虚数

<ipython-input-47-684a50b9c32a>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)  # 虚数


False

# 如何获得昨天，今天和明天的日期? (★☆☆)

In [48]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday, today, tomorrow

(numpy.datetime64('2021-06-17'),
 numpy.datetime64('2021-06-18'),
 numpy.datetime64('2021-06-19'))

# 怎么获得所有与2016年7月的所有日期? (★★☆)

In [49]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# 如何计算 ((A+B)*(-A/2)) (不使用中间变量)? (★★☆)

In [50]:
A = np.ones(3) * 1
B = np.ones(3) * 1
C = np.ones(3) * 1
print(A, B, C)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

[1. 1. 1.] [1. 1. 1.] [1. 1. 1.]


array([-1., -1., -1.])

# 用5种不同的方法提取随机数组中的整数部分 (★★☆)

In [51]:
Z = np.random.uniform(0, 10, 10)
print(Z)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[4.90411312 2.22030408 7.395821   3.78739127 9.67764845 0.79156236
 7.48234394 4.97113807 7.38026302 1.04932195]
[4. 2. 7. 3. 9. 0. 7. 4. 7. 1.]
[4. 2. 7. 3. 9. 0. 7. 4. 7. 1.]
[4. 2. 7. 3. 9. 0. 7. 4. 7. 1.]
[4 2 7 3 9 0 7 4 7 1]
[4. 2. 7. 3. 9. 0. 7. 4. 7. 1.]


# 创建一个5x5的矩阵且每一行的值范围为从0到4 (★★☆)

In [52]:
Z = np.zeros((5, 5))
Z += np.arange(5)
Z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# 如何用一个生成10个整数的函数来构建数组 (★☆☆)

In [53]:
def generate():
    for x in range(10):
      yield x
np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# 创建一个大小为10的向量， 值域为0到1，不包括0和1 (★★☆)

In [54]:
np.linspace(0, 1, 12, endpoint=True)[1: -1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

# 创建一个大小为10的随机向量，并把它排序 (★★☆)

In [55]:
Z = np.random.random(10)
print(Z)
Z.sort()
print(Z)

[0.6732877  0.09483093 0.62980298 0.31650102 0.65958832 0.77948782
 0.45246067 0.13698674 0.80389719 0.50540976]
[0.09483093 0.13698674 0.31650102 0.45246067 0.50540976 0.62980298
 0.65958832 0.6732877  0.77948782 0.80389719]


# 对一个小数组进行求和有没有办法比np.sum更快? (★★☆)

In [56]:
Z = np.arange(10)
print(Z)
np.add.reduce(Z)

[0 1 2 3 4 5 6 7 8 9]


45

# 如何判断两和随机数组相等 (★★☆)

In [57]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# 假设array的形状(shape)相同和一个误差容限（tolerance）
equal = np.allclose(A,B)
print(equal)

# 检查形状和元素值，没有误差容限（值必须完全相等）
equal = np.array_equal(A,B)
print(equal)

False
False


# 把数组变为只读 (★★☆)

In [58]:
Z = np.zeros(5)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

# 将一个10x2的笛卡尔坐标矩阵转换为极坐标 (★★☆)

In [59]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print (R)
print (T)

[1.01122579 0.93031672 0.42857143 0.76436289 0.88591214 0.5330413
 0.9897492  0.65324326 0.33586976 0.89793737]
[0.35012305 0.51995759 0.71247213 0.74883824 1.11931432 0.65445006
 1.19783637 0.64715609 1.09585639 0.12675273]


# 创建一个大小为10的随机向量并且将该向量中最大的值替换为0(★★☆)

In [60]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
Z

array([0.7535488 , 0.68031411, 0.60016447, 0.45633223, 0.69777746,
       0.        , 0.14584176, 0.54110602, 0.4263355 , 0.43242272])

# 创建一个结构化数组，其中x和y坐标覆盖[0, 1]x[1, 0]区域 (★★☆)

In [61]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

# 给定两个数组X和Y，构造柯西(Cauchy)矩阵C(★★☆)

In [62]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print (C)
print(np.linalg.det(C))  # 计算行列式

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


# 打印每个numpy类型的最小和最大可表示值 (★★☆)

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 如何打印数组中所有的值？(★★☆)

In [64]:
np.set_printoptions(threshold=sys.maxsize)
np.zeros((16,16))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

# 如何在数组中找到与给定标量接近的值? (★★☆)

In [65]:
Z = np.arange(100)
print(Z)
v = np.random.uniform(0, 100)
print(v)
index = (np.abs(Z-v)).argmin()
print(index)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
84.35177925686922
84
84
